//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EProject.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jwelleryEntities : DbContext
    {
        public jwelleryEntities()
            : base("name=jwelleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminloginMst> AdminloginMsts { get; set; }
        public virtual DbSet<BrandMst> BrandMsts { get; set; }
        public virtual DbSet<CartList> CartLists { get; set; }
        public virtual DbSet<CatMst> CatMsts { get; set; }
        public virtual DbSet<CertifyMst> CertifyMsts { get; set; }
        public virtual DbSet<DimInfoMst> DimInfoMsts { get; set; }
        public virtual DbSet<DimQltyMst> DimQltyMsts { get; set; }
        public virtual DbSet<DimQlySubMst> DimQlySubMsts { get; set; }
        public virtual DbSet<GoldKrtMst> GoldKrtMsts { get; set; }
        public virtual DbSet<Inquiry> Inquiries { get; set; }
        public virtual DbSet<ItemMst> ItemMsts { get; set; }
        public virtual DbSet<JewelTypeMst> JewelTypeMsts { get; set; }
        public virtual DbSet<ProdMst> ProdMsts { get; set; }
        public virtual DbSet<StoneQltyMst> StoneQltyMsts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserRegMst> UserRegMsts { get; set; }
        public virtual DbSet<DimMst> DimMsts { get; set; }
        public virtual DbSet<StoneMst> StoneMsts { get; set; }
    }
}
